services:
  - type: worker
    name: discord-wallet-bot
    env: node
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: DISCORD_TOKEN
        sync: false
